# Generated by Django 3.0.7 on 2020-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200624_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_cover',
            field=models.ImageField(default='cover.jpg', upload_to='profile_cover'),
        ),
    ]
